anguage: ruby
rvm:
  - "2.3.1"
script:
  - RAILS_ENV=test bundle exec rake db:schema:load
  - RAILS_ENV=test db:migrate
  - RAILS_ENV=test db:seed
  - RAILS_ENV=test db:test:prepare
  - bundle exec rspec spec/
bundler_args: --binstubs=./bundler_stubs